title:              My Jane
email:              myjaneausten@gmail.com
description:        Emily's Blog!
author:             Emily Christ
baseurl:            "/"
url:                "https://www.myjaneausten.com"

# Social Profiles
twitter_username:   myjaneausten42
github_username:    emily565
facebook_username:  
instagram_username:  
linkedin_username:  emily-christ-b46387121

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
